@echo off
echo ====================================================
echo       Tobal Flexy Desktop Compiler Wizard
echo ====================================================
echo.
echo [!] Stopping any running instances of the app to prevent locks...
taskkill /F /IM "Tobal Flexy Desktop.exe" /IM "electron.exe" /IM "node.exe" /T >nul 2>&1
timeout /t 2 >nul

echo.
echo [1/2] Cleaning up unnecessary debug screenshots and obsolete files...
:: Delete debug screenshots generated by Puppeteer
del /f /q fail_step1_attempt_1.png fail_step1_attempt_2.png fail_step1_attempt_3.png last_captcha.png last_recharge_status.png step2_debug.png step2_debug.html >nul 2>&1

:: Delete old obsolete web server files (no longer used in desktop app)
del /f /q index.html script.js style.css sim_dashboard.html sim_script.js sim_style.css >nul 2>&1

echo [+] Cleanup completed successfully!

echo.
echo [2/2] Compiling the program into a stand-alone installer...
echo Please wait, this will take less than 30 seconds...
echo.
call npm run build
echo.
if %errorlevel% neq 0 (
    echo.
    echo [!] ERROR: Compilation failed!
    echo Please make sure Node.js is installed.
) else (
    echo.
    echo [+] SUCCESS: Program compiled successfully!
    echo [+] The installer (.exe) is saved inside the [dist] folder.
    echo.
    echo Opening the [dist] folder in Explorer so you can install the new version...
    explorer dist
)
echo.
echo ====================================================
pause
